name: super_brain
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  cloud_firestore: ^6.0.1
  file_picker: ^10.3.2
  firebase_auth: ^6.0.2
  firebase_core: ^4.1.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_web_plugins:
    sdk: flutter
  freezed_annotation: ^3.1.0
  go_router: ^16.2.1
  google_fonts: ^6.3.1
  google_sign_in: ^6.2.1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  phone_form_field: ^10.0.10
  sign_in_with_apple: ^6.1.2

dev_dependencies:
  build_runner: ^2.7.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.0
  json_serializable: ^6.11.0

flutter:
  uses-material-design: true

  assets:
    - assets/data/
