// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN6TL06PAqfWRCtfmwle8WtnlRZVxSkww',
    appId: '1:467274672074:web:cb8efb87e61325f030d133',
    messagingSenderId: '467274672074',
    projectId: 'superbrain-feldrise',
    authDomain: 'superbrain-feldrise.firebaseapp.com',
    storageBucket: 'superbrain-feldrise.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKCuEr4iDK352wJb0dy53hd3bouRJpxoM',
    appId: '1:467274672074:android:2b4708270dbc490e30d133',
    messagingSenderId: '467274672074',
    projectId: 'superbrain-feldrise',
    storageBucket: 'superbrain-feldrise.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-woKYA59JhB3EteYAmWu0HvEvxvzOm1s',
    appId: '1:467274672074:ios:6dc9b80ff6ea19fa30d133',
    messagingSenderId: '467274672074',
    projectId: 'superbrain-feldrise',
    storageBucket: 'superbrain-feldrise.firebasestorage.app',
    iosClientId: '467274672074-igjdh0vgpnc3nkakrpvfrtp060k8hu0l.apps.googleusercontent.com',
    iosBundleId: 'com.feldrise.superBrain',
  );

}